# Generated by Django 2.1.7 on 2019-04-07 20:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('signals_practice', '0003_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_proxy_model',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
